spring:
  profiles:
    active: dev
  application:
    name: inmanage-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: inmanage-service
  datasource:
    name: inmanage
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3307/bank_base?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
    mvc:
      view:
        prefix: /
        suffix: .html
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package:
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count==countSql
